name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.38'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: WrenDoc.PL
        run: perl src/scripts/WrenDocs.pl -out Test.md -in src/scripts/io.wren
      - name: update file and push to remote
        run: |
          git config user.name "dollerama"
          git config user.email "graham.p.sullivan@gmail.com"
          
          git add -A
          git commit -m "Update doc"
          git push
