name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.38'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: WrenDoc.PL
        run: perl src/scripts/WrenDocs.pl -out LilahScriptingAPI.md -in src/scripts/io.wren,src/scripts/game.wren,src/scripts/ParticleSystem.wren,src/scripts/Trail.wren,src/scripts/app.wren,src/scripts/math.wren
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add -A
          git commit -m "updating wren doc"
          git push
